package com.termux.app.themes;

import android.content.Context;

import com.termux.app.TermuxActivity;
import com.termux.shared.logger.Logger;
import com.termux.shared.termux.TermuxConstants;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;

public class ThemeManager {

    private static final String LOG_TAG = "ThemeManager";

    public static void applyTheme(Context context, ThemePreset theme) {
        if (context == null || theme == null) return;

        File colorsFile = TermuxConstants.TERMUX_COLOR_PROPERTIES_FILE;
        File parentDir = colorsFile.getParentFile();

        if (parentDir != null && !parentDir.exists()) {
            parentDir.mkdirs();
        }

        Properties props = new Properties();
        props.setProperty("background", theme.backgroundColor);
        props.setProperty("foreground", theme.foregroundColor);
        props.setProperty("cursor", theme.cursorColor);

        for (int i = 0; i < theme.ansiColors.length; i++) {
            props.setProperty("color" + i, theme.ansiColors[i]);
        }

        try (FileOutputStream out = new FileOutputStream(colorsFile)) {
            props.store(out, "Auto-generated by TermuxMod Theme Switcher");
            Logger.logInfo(LOG_TAG, "Applied theme: " + theme.name);
        } catch (IOException e) {
            Logger.logStackTraceWithMessage(LOG_TAG, "Failed to write theme properties", e);
            return;
        }

        TermuxActivity.updateTermuxActivityStyling(context, false);
    }
}